### ISSUE TITLE
Vocabulary is auto generated for $identifier

### ISSUE THREAD

**Issue by apoorvsxna** [accordproject/concerto-codegen#97]
## Bug Report 🐛
This issue may be considered a follow-up to [this](https://github.com/accordproject/concerto/issues/776) issue in the concerto repository.

Vocabulary is auto-generated for $identifier, while it is supposed to be skipped in this case.

## Expected Behavior
Should not auto generate vocabulary for $identifier

## Current Behavior
For this model,
``` namespace org.acme@1.0.0

concept Person identified {
	o String name
}

enum Color {
    o RED
    o BLUE
    o GREEN
}

asset Vehicle identified by vin {
    o String vin
    o Color color
}

asset Truck extends Vehicle {
    o Double weight
}
```
The following vocab is generated.
```
#Generated vocabulary for namespace: org.acme@1.0.0
locale: en
namespace: org.acme@1.0.0
declarations:
  - Person: Person
    properties:
      - $identifier: Identifier of the Person # should not be auto generated
      - name: Name of the Person
  - Color: Color
    properties:
      - RED: RED of the Color
      - BLUE: BLUE of the Color
      - GREEN: GREEN of the Color
  - Vehicle: Vehicle
    properties:
      - vin: Vin of the Vehicle
      - color: Color of the Vehicle
  - Truck: Truck
    properties:
      - weight: Weight of the Truck
```
## Possible Solution
Fix bug in vocabularyvisitor.js in the concerto-codegen repository.

## Steps to Reproduce

1. Run
```
concerto compile --target vocabulary
``` 
for the above .cto file.
